openapi: 3.1.0
info:
  title: Ingestor API
  version: 1.0.0
paths:
  "/projects/{token}":
    get:
      summary: Get a project by share token
      operationId: getRequest
      parameters:
        - $ref: '#/components/parameters/ShareToken'
      responses:
        "200":
          $ref: '#/components/responses/ProjectResponse'
        #"404":
        #  $ref: "#/components/responses/NotFound"
        #"500":
        #  $ref: "#/components/responses/InternalServerErrror"
components:
  parameters:
    ShareToken:
      name: token
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Token'
  responses:
    ProjectResponse:
      description: "Successfully retrieved a project by its share token"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Project'
  schemas:
    Project:
      type: object
      required: [id, share_token, description, updated_at, created_at]
      properties:
        id:
          $ref: '#/components/schemas/ProjectId'
        share_token:
          $ref: '#/components/schemas/Token'
        admin_token:
          $ref: '#/components/schemas/Token'
        description:
          type: string
        updated_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
    ProjectId:
      type: string
      format: uuid
      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[89abAB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}"
    Token:
      type: string
      pattern: "[abcdefgijkmnopqrstwxyzABCDEFGHJKLMNPQRSTWXYZ23456789]{16}"
