// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Pong = {
    message: 'pong';
};

export type Project = {
    id: ProjectId;
    share_token: Token;
    admin_token?: Token;
    description: ProjectDescription;
    filename_format: FilenameFormat;
    updated_at: string;
    created_at: string;
};

export type User = {
    id: UserId;
    name: Username;
    updated_at: string;
    created_at: string;
};

export type ProjectId = string;

export type MediaId = string;

export type UserId = string;

export type Token = string;

export type RequestId = string;

export type ErrorResponse = {
    message: string;
    code: number;
    traceback?: string;
    details?: {
        [key: string]: unknown;
    };
};

export type ProblemDetails = {
    /**
     * A URI reference that identifies the problem type. When omitted, it is assumed to be "about:blank".
     */
    type: string;
    /**
     * A short, human-readable summary of the problem type.
     */
    title: string;
    /**
     * The HTTP status code generated by the origin server for this occurrence of the problem.
     */
    status: number;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail: string;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    [key: string]: unknown;
};

export type NewProject = {
    description: ProjectDescription;
    filename_format?: FilenameFormat;
};

export type ProjectPatch = {
    description?: ProjectDescription;
    filename_format?: FilenameFormat;
};

export type PagedProjects = {
    projects: Array<Project>;
    page: number;
    per_page: number;
    total: number;
};

export type PagedUsers = {
    users: Array<User>;
    page: number;
    per_page: number;
    total: number;
};

export type NewUser = {
    name: Username;
};

export type Image = {
    id: MediaId;
    type: 'image';
    original_filename: string;
    generated_filename: string;
    width: number;
    height: number;
    image_codec: string;
    time_correction_offset?: string;
};

export type Video = {
    id: MediaId;
    type: 'video';
    original_filename: string;
    generated_filename: string;
    width: number;
    height: number;
    length: string;
    video_codec: string;
    time_correction_offset?: string;
};

export type Media = ({
    type: 'image';
} & Image) | ({
    type: 'video';
} & Video);

export type MediaUpdate = {
    original_filename?: string;
    time_correction_offset?: string;
};

export type UserUpdate = {
    name?: Username;
};

/**
 * A time format that follows the go Time.Format specification. See https://pkg.go.dev/time#Layout
 */
export type FilenameFormat = string;

export type ProjectDescription = string;

/**
 * A user's name
 */
export type Username = string;

export type ShareToken = Token;

export type AdminToken = Token;

export type MediaId2 = MediaId;

export type UserId2 = UserId;

export type Page = number;

export type PerPage = number;

export type RequestId2 = RequestId;

export type GetPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ping';
};

export type GetPingResponses = {
    /**
     * The server is alive
     */
    200: Pong;
};

export type GetPingResponse = GetPingResponses[keyof GetPingResponses];

export type ListProjectsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        per_page?: number;
    };
    url: '/projects';
};

export type ListProjectsErrors = {
    /**
     * An internal server error occurred
     */
    500: ProblemDetails;
};

export type ListProjectsError = ListProjectsErrors[keyof ListProjectsErrors];

export type ListProjectsResponses = {
    /**
     * A page of projects
     */
    200: PagedProjects;
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type CreateProjectData = {
    body: NewProject;
    headers: {
        'X-Request-ID': RequestId;
    };
    path?: never;
    query?: never;
    url: '/projects';
};

export type CreateProjectErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails;
    /**
     * An internal server error occurred
     */
    500: ProblemDetails;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * A single project
     */
    201: Project;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type GetRequestData = {
    body?: never;
    path: {
        token: Token;
    };
    query?: never;
    url: '/projects/{token}';
};

export type GetRequestErrors = {
    /**
     * The requested project was not found
     */
    404: ProblemDetails;
    /**
     * An internal server error occurred
     */
    500: ProblemDetails;
};

export type GetRequestError = GetRequestErrors[keyof GetRequestErrors];

export type GetRequestResponses = {
    /**
     * A single project
     */
    200: Project;
};

export type GetRequestResponse = GetRequestResponses[keyof GetRequestResponses];

export type ListUsersData = {
    body?: never;
    path: {
        token: Token;
    };
    query?: {
        page?: number;
        per_page?: number;
    };
    url: '/projects/{token}/users';
};

export type ListUsersErrors = {
    /**
     * An internal server error occurred
     */
    500: ProblemDetails;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * A page of users for a project
     */
    200: PagedUsers;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: NewUser;
    path: {
        token: Token;
    };
    query?: never;
    url: '/projects/{token}/users';
};

export type CreateUserErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails;
    /**
     * An internal server error occurred
     */
    500: ProblemDetails;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * A single user
     */
    201: User;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        token: Token;
        'user-id': UserId;
    };
    query?: never;
    url: '/projects/{token}/users/{user-id}';
};

export type GetUserErrors = {
    /**
     * The requested project was not found
     */
    404: ProblemDetails;
    /**
     * An internal server error occurred
     */
    500: ProblemDetails;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * A single user
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type PatchUserData = {
    body: UserUpdate;
    path: {
        token: Token;
        'user-id': UserId;
    };
    query?: never;
    url: '/projects/{token}/users/{user-id}';
};

export type PatchUserErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails;
    /**
     * The requested project was not found
     */
    404: ProblemDetails;
    /**
     * An internal server error occurred
     */
    500: ProblemDetails;
};

export type PatchUserError = PatchUserErrors[keyof PatchUserErrors];

export type PatchUserResponses = {
    /**
     * A single user
     */
    200: User;
};

export type PatchUserResponse = PatchUserResponses[keyof PatchUserResponses];

export type UploadMediaData = {
    body: {
        file: Blob | File;
    };
    path: {
        token: Token;
    };
    query?: never;
    url: '/projects/{token}/media';
};

export type UploadMediaErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails;
    /**
     * The requested project was not found
     */
    404: ProblemDetails;
    /**
     * An internal server error occurred
     */
    500: ProblemDetails;
};

export type UploadMediaError = UploadMediaErrors[keyof UploadMediaErrors];

export type UploadMediaResponses = {
    /**
     * Media metadata
     */
    201: Media;
};

export type UploadMediaResponse = UploadMediaResponses[keyof UploadMediaResponses];

export type GetMediaData = {
    body?: never;
    path: {
        token: Token;
        'media-id': MediaId;
    };
    query?: never;
    url: '/projects/{token}/media/{media-id}';
};

export type GetMediaErrors = {
    /**
     * The requested project was not found
     */
    404: ProblemDetails;
    /**
     * An internal server error occurred
     */
    500: ProblemDetails;
};

export type GetMediaError = GetMediaErrors[keyof GetMediaErrors];

export type GetMediaResponses = {
    /**
     * Media metadata
     */
    200: Media;
};

export type GetMediaResponse = GetMediaResponses[keyof GetMediaResponses];

export type UpdateMediaData = {
    body: MediaUpdate;
    path: {
        token: Token;
        'media-id': MediaId;
    };
    query?: never;
    url: '/projects/{token}/media/{media-id}';
};

export type UpdateMediaErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails;
    /**
     * The requested project was not found
     */
    404: ProblemDetails;
    /**
     * An internal server error occurred
     */
    500: ProblemDetails;
};

export type UpdateMediaError = UpdateMediaErrors[keyof UpdateMediaErrors];

export type UpdateMediaResponses = {
    /**
     * Media metadata
     */
    200: Media;
};

export type UpdateMediaResponse = UpdateMediaResponses[keyof UpdateMediaResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        token: Token;
    };
    query?: never;
    url: '/projects/admin/{token}';
};

export type DeleteProjectErrors = {
    /**
     * The requested project was not found
     */
    404: ProblemDetails;
    /**
     * An internal server error occurred
     */
    500: ProblemDetails;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * The project was deleted
     */
    204: void;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type PatchProjectData = {
    body: ProjectPatch;
    headers: {
        'X-Request-ID': RequestId;
    };
    path: {
        token: Token;
    };
    query?: never;
    url: '/projects/admin/{token}';
};

export type PatchProjectErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails;
    /**
     * The requested project was not found
     */
    404: ProblemDetails;
    /**
     * An internal server error occurred
     */
    500: ProblemDetails;
};

export type PatchProjectError = PatchProjectErrors[keyof PatchProjectErrors];

export type PatchProjectResponses = {
    /**
     * A single project
     */
    200: Project;
};

export type PatchProjectResponse = PatchProjectResponses[keyof PatchProjectResponses];

export type UpdateProjectData = {
    body: NewProject;
    headers: {
        'X-Request-ID': RequestId;
    };
    path: {
        token: Token;
    };
    query?: never;
    url: '/projects/admin/{token}';
};

export type UpdateProjectErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails;
    /**
     * The requested project was not found
     */
    404: ProblemDetails;
    /**
     * An internal server error occurred
     */
    500: ProblemDetails;
};

export type UpdateProjectError = UpdateProjectErrors[keyof UpdateProjectErrors];

export type UpdateProjectResponses = {
    /**
     * A single project
     */
    200: Project;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type DeleteMediaData = {
    body?: never;
    path: {
        token: Token;
        'media-id': MediaId;
    };
    query?: never;
    url: '/projects/admin/{token}/media/{media-id}';
};

export type DeleteMediaErrors = {
    /**
     * The requested project was not found
     */
    404: ProblemDetails;
    /**
     * An internal server error occurred
     */
    500: ProblemDetails;
};

export type DeleteMediaError = DeleteMediaErrors[keyof DeleteMediaErrors];

export type DeleteMediaResponses = {
    /**
     * The media was deleted
     */
    204: void;
};

export type DeleteMediaResponse = DeleteMediaResponses[keyof DeleteMediaResponses];
