// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type Pong = {
    message: 'pong';
};

export type SystemCapabilities = {
    supported_transcoding_presets: Array<TranscodePreset>;
    ffmpeg_path: string;
    /**
     * The ffmpeg version, as reported by ffmpeg -version
     */
    ffmpeg_version: string;
};

export type Project = {
    id: ProjectId;
    share_token: Token;
    admin_token?: Token;
    description: ProjectDescription;
    share_token_permissions: Array<ProjectShareTokenPermission>;
    start: ProjectStart;
    end: ProjectEnd;
    expires_at: ProjectExpiry;
    updated_at: string;
    created_at: string;
};

export type User = {
    id: UserId;
    name: Username;
    updated_at: string;
    created_at: string;
};

export type Job = {
    id: JobId;
    type: JobType;
    status: JobStatus;
    description: string;
    updated_at: string;
    created_at: string;
    [key: string]: unknown;
};

export type ProjectId = string;

export type MediaId = string;

export type UserId = string;

export type JobId = string;

export type FilteredDownloadToken = Token;

export type Token = string;

export type ProblemDetails = {
    /**
     * A URI reference that identifies the problem type. When omitted, it is assumed to be "about:blank".
     */
    type?: string;
    /**
     * A short, human-readable summary of the problem type.
     */
    title?: string;
    /**
     * The HTTP status code generated by the origin server for this occurrence of the problem.
     */
    status?: number;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    [key: string]: unknown;
};

export type Page = {
    page_num: unknown;
    per_page: number;
    total: number;
};

export type NewProject = {
    description: ProjectDescription;
    start?: ProjectStart;
    end?: ProjectEnd;
    expires_at?: ProjectExpiry;
    share_token_permissions?: Array<ProjectShareTokenPermission>;
};

export type ProjectUpdate = {
    description?: ProjectDescription;
    start?: ProjectStart;
    end?: ProjectEnd;
    expires_at?: ProjectExpiry;
    share_token_permissions?: Array<ProjectShareTokenPermission>;
    /**
     * Invalidate the previous share token and let the server generate a new one.
     */
    rotate_share_token?: boolean;
    /**
     * Invalidate the previous admin token and let the server generate a new one. Be aware that when rotated, the admin token (used in this request) will not work anymore.
     */
    rotate_admin_token?: boolean;
};

export type MediaBatchDeletionRequest = {
    media_ids?: Array<MediaId>;
};

export type PagedProjects = {
    page: Page;
    projects: Array<Project>;
};

export type PagedMediaMetadata = {
    page: Page;
    media_metadata: Array<MediaMetadata>;
};

export type PagedUsers = {
    users: Array<User>;
    page: Page;
};

export type PagedJobs = {
    jobs: Array<Job>;
    page: Page;
};

export type NewUser = {
    name: Username;
};

export type ImageMetadata = {
    id: MediaId;
    type: 'image';
    original_filename: string;
    generated_filename: string;
    width: number;
    height: number;
    image_codec: string;
    mime_type: string;
    original_capture_time: string;
    time_correction_offset: string;
};

export type VideoMetadata = {
    id: MediaId;
    type: 'video';
    original_filename: string;
    generated_filename: string;
    width: number;
    height: number;
    length: string;
    video_codec: string;
    mime_type: string;
    original_capture_time: string;
    time_correction_offset: string;
};

export type MediaMetadata = ({
    type: 'image';
} & ImageMetadata) | ({
    type: 'video';
} & VideoMetadata);

export type MediaMetadataUpdate = {
    original_filename?: string;
    time_correction_offset?: string;
};

export type MediaMetadataTimesync = {
    media_ids_to_sync: Array<MediaId>;
};

export type UserUpdate = {
    name?: Username;
};

export type NewFilteredDownload = {
    included_media_ids: Array<MediaId>;
    excluded_media_ids: Array<MediaId>;
    included_user_ids: Array<UserId>;
    excluded_user_ids: Array<UserId>;
    capture_time_start?: CaptureRangeStartInclusive;
    capture_time_end?: CaptureRangeEndExclusive;
    /**
     * If no value is given, this is set automatically by the server to a reasonable time.
     */
    expires_at?: FilteredDownloadExpiry;
};

export type FilteredDownload = {
    download_token: Token;
    included_media_ids: Array<MediaId>;
    excluded_media_ids: Array<MediaId>;
    included_user_ids: Array<UserId>;
    excluded_user_ids: Array<UserId>;
    capture_time_start: CaptureRangeStartInclusive | null;
    capture_time_end: CaptureRangeEndExclusive | null;
    expires_at: FilteredDownloadExpiry;
};

/**
 * A time format that follows the go Time.Format specification. See https://pkg.go.dev/time#Layout
 */
export type FilenameFormat = string;

export type ProjectDescription = string;

/**
 * The start date and time of the project (event). Used for finding media that does not fall into the project time range.
 */
export type ProjectStart = string;

/**
 * The end date and time of the project (event). Used for finding media that does not fall into the project time range.
 */
export type ProjectEnd = string;

/**
 * Expiry date for the project. After that time, the project is automatically deleted.
 */
export type ProjectExpiry = string;

/**
 * Exclude media that has a capture time (with correction offset) before this time.
 */
export type CaptureRangeStartInclusive = string;

/**
 * Exclude media that has a capture time (with correction offset) at or after this time.
 */
export type CaptureRangeEndExclusive = string;

/**
 * The time at or after the prepared download link will automatically be deleted. Does not influence any media deletions.
 */
export type FilteredDownloadExpiry = string;

/**
 * The actions allowed to perform via the share token.
 */
export type ProjectShareTokenPermission = 'upload' | 'download';

/**
 * A user's name
 */
export type Username = string;

export type TranscodePreset = 'h264-2160p' | 'h264-1440p' | 'h264-1080p' | 'h264-720p' | 'h264-480p' | 'h265-2160p' | 'h265-1440p' | 'h265-1080p' | 'h265-720p' | 'h265-480p';

/**
 * A job's type
 */
export type JobType = 'transcode' | 'thumbnail';

/**
 * A job's status
 */
export type JobStatus = 'created' | 'running' | 'success' | 'failed';

export type DownloadFile = Blob | File;

/**
 * Crop mode:
 * - `center`: Image dimensions are kept and the image is scaled to fit the given width and height. No black bars are present.
 * - `stretch`: Image dimensions are *not* kept and the image is scaled and stretched to fit the given width and height. No black bars are present.
 * - `box`: Image dimensions are kept and the image is scaled to fit inside the given width and height. Black bars (pillorboxing/letterboxing) might occur.
 *
 */
export type PreviewCropMode = 'center' | 'stretch' | 'box';

/**
 * The requested preview image has not been created yet, try again later.
 */
export type ProjectMediaPreviewNotReadyYet = {
    preview_status: 'pending';
};

export type ShareToken = Token;

export type AdminToken = Token;

export type MediaId2 = MediaId;

export type PreviewWidth = number;

export type PreviewHeight = number;

export type PreviewCropMode2 = PreviewCropMode;

export type UserId2 = UserId;

export type FilteredDownloadToken2 = Token;

export type PageNum = number;

export type PageSize = number;

export type FilterJobType = Array<JobType>;

export type FilterJobStatus = Array<JobStatus>;

export type FilenameFormat2 = FilenameFormat;

export type GetPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ping';
};

export type GetPingResponses = {
    /**
     * The server is alive
     */
    200: Pong;
};

export type GetPingResponse = GetPingResponses[keyof GetPingResponses];

export type GetSystemCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/capabilities';
};

export type GetSystemCapabilitiesResponses = {
    /**
     * The system's capabilities, such as supported transcoding qualities.
     */
    200: SystemCapabilities;
};

export type GetSystemCapabilitiesResponse = GetSystemCapabilitiesResponses[keyof GetSystemCapabilitiesResponses];

export type ListProjectsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        per_page?: number;
    };
    url: '/projects';
};

export type ListProjectsErrors = {
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type ListProjectsError = ListProjectsErrors[keyof ListProjectsErrors];

export type ListProjectsResponses = {
    /**
     * A page of projects
     */
    200: PagedProjects;
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type CreateProjectData = {
    body: NewProject;
    path?: never;
    query?: never;
    url: '/projects';
};

export type CreateProjectErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails & {
        title: 'The request was malformed or invalid.';
        status: 400;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * A single project
     */
    201: Project;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type GetProjectByShareTokenData = {
    body?: never;
    path: {
        'share-token': Token;
    };
    query?: never;
    url: '/projects/{share-token}';
};

export type GetProjectByShareTokenErrors = {
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type GetProjectByShareTokenError = GetProjectByShareTokenErrors[keyof GetProjectByShareTokenErrors];

export type GetProjectByShareTokenResponses = {
    /**
     * A single project
     */
    200: Project;
};

export type GetProjectByShareTokenResponse = GetProjectByShareTokenResponses[keyof GetProjectByShareTokenResponses];

export type ListProjectUsersData = {
    body?: never;
    path: {
        'share-token': Token;
    };
    query?: {
        page?: number;
        per_page?: number;
    };
    url: '/projects/{share-token}/users';
};

export type ListProjectUsersErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails & {
        title: 'The request was malformed or invalid.';
        status: 400;
    };
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type ListProjectUsersError = ListProjectUsersErrors[keyof ListProjectUsersErrors];

export type ListProjectUsersResponses = {
    /**
     * A page of users for a project
     */
    200: PagedUsers;
};

export type ListProjectUsersResponse = ListProjectUsersResponses[keyof ListProjectUsersResponses];

export type CreateProjectUserData = {
    body: NewUser;
    path: {
        'share-token': Token;
    };
    query?: never;
    url: '/projects/{share-token}/users';
};

export type CreateProjectUserErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails & {
        title: 'The request was malformed or invalid.';
        status: 400;
    };
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type CreateProjectUserError = CreateProjectUserErrors[keyof CreateProjectUserErrors];

export type CreateProjectUserResponses = {
    /**
     * A single user
     */
    201: User;
};

export type CreateProjectUserResponse = CreateProjectUserResponses[keyof CreateProjectUserResponses];

export type GetProjectUserData = {
    body?: never;
    path: {
        'share-token': Token;
        'user-id': UserId;
    };
    query?: never;
    url: '/projects/{share-token}/users/{user-id}';
};

export type GetProjectUserErrors = {
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type GetProjectUserError = GetProjectUserErrors[keyof GetProjectUserErrors];

export type GetProjectUserResponses = {
    /**
     * A single user
     */
    200: User;
};

export type GetProjectUserResponse = GetProjectUserResponses[keyof GetProjectUserResponses];

export type PatchProjectUserData = {
    body: UserUpdate;
    path: {
        'share-token': Token;
        'user-id': UserId;
    };
    query?: never;
    url: '/projects/{share-token}/users/{user-id}';
};

export type PatchProjectUserErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails & {
        title: 'The request was malformed or invalid.';
        status: 400;
    };
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type PatchProjectUserError = PatchProjectUserErrors[keyof PatchProjectUserErrors];

export type PatchProjectUserResponses = {
    /**
     * A single user
     */
    200: User;
};

export type PatchProjectUserResponse = PatchProjectUserResponses[keyof PatchProjectUserResponses];

export type GetProjectBackgroundJobsData = {
    body?: never;
    path: {
        'share-token': Token;
    };
    query?: {
        page?: number;
        per_page?: number;
        type?: Array<JobType>;
        status?: Array<JobStatus>;
    };
    url: '/projects/{share-token}/jobs';
};

export type GetProjectBackgroundJobsErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails & {
        title: 'The request was malformed or invalid.';
        status: 400;
    };
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type GetProjectBackgroundJobsError = GetProjectBackgroundJobsErrors[keyof GetProjectBackgroundJobsErrors];

export type GetProjectBackgroundJobsResponses = {
    /**
     * A page of jobs
     */
    200: PagedJobs;
};

export type GetProjectBackgroundJobsResponse = GetProjectBackgroundJobsResponses[keyof GetProjectBackgroundJobsResponses];

export type ListProjectMediaMetadataData = {
    body?: never;
    path: {
        'share-token': Token;
    };
    query?: {
        page?: number;
        per_page?: number;
    };
    url: '/projects/{share-token}/media';
};

export type ListProjectMediaMetadataErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails & {
        title: 'The request was malformed or invalid.';
        status: 400;
    };
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type ListProjectMediaMetadataError = ListProjectMediaMetadataErrors[keyof ListProjectMediaMetadataErrors];

export type ListProjectMediaMetadataResponses = {
    /**
     * A page of media metadata
     */
    200: PagedMediaMetadata;
};

export type ListProjectMediaMetadataResponse = ListProjectMediaMetadataResponses[keyof ListProjectMediaMetadataResponses];

export type UploadProjectMediaData = {
    body: {
        file?: Array<unknown>;
    };
    path: {
        'share-token': Token;
    };
    query?: never;
    url: '/projects/{share-token}/media/upload';
};

export type UploadProjectMediaErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails & {
        title: 'The request was malformed or invalid.';
        status: 400;
    };
    /**
     * The admin has not yet enabled uploads for this project.
     */
    403: ProblemDetails & {
        title: 'The admin has not yet enabled uploads for this project.';
        status: 403;
    };
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type UploadProjectMediaError = UploadProjectMediaErrors[keyof UploadProjectMediaErrors];

export type UploadProjectMediaResponses = {
    /**
     * Media metadata ids for all uploaded files.
     */
    201: {
        created_media_ids: Array<MediaId>;
    };
};

export type UploadProjectMediaResponse = UploadProjectMediaResponses[keyof UploadProjectMediaResponses];

export type DownloadProjectMediaArchiveData = {
    body?: never;
    path: {
        'share-token': Token;
    };
    query?: {
        filename_format?: FilenameFormat;
    };
    url: '/projects/{share-token}/media/download';
};

export type DownloadProjectMediaArchiveErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails & {
        title: 'The request was malformed or invalid.';
        status: 400;
    };
    /**
     * The admin has not yet enabled downloads for this project.
     */
    403: ProblemDetails & {
        title: 'The admin has not yet enabled downloads for this project.';
        status: 403;
    };
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type DownloadProjectMediaArchiveError = DownloadProjectMediaArchiveErrors[keyof DownloadProjectMediaArchiveErrors];

export type DownloadProjectMediaArchiveResponses = {
    /**
     * Project media, archived as a zip or tar file. If mime type is application/octet-stream, the zip file is served.
     */
    200: DownloadFile;
};

export type DownloadProjectMediaArchiveResponse = DownloadProjectMediaArchiveResponses[keyof DownloadProjectMediaArchiveResponses];

export type CreateDownloadProjectFilteredMediaArchiveData = {
    body: NewFilteredDownload;
    path: {
        'share-token': Token;
    };
    query?: never;
    url: '/projects/{share-token}/media/download/filtered';
};

export type CreateDownloadProjectFilteredMediaArchiveErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails & {
        title: 'The request was malformed or invalid.';
        status: 400;
    };
    /**
     * The admin has not yet enabled downloads for this project.
     */
    403: ProblemDetails & {
        title: 'The admin has not yet enabled downloads for this project.';
        status: 403;
    };
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type CreateDownloadProjectFilteredMediaArchiveError = CreateDownloadProjectFilteredMediaArchiveErrors[keyof CreateDownloadProjectFilteredMediaArchiveErrors];

export type CreateDownloadProjectFilteredMediaArchiveResponses = {
    /**
     * A single filtered download
     */
    200: FilteredDownload;
};

export type CreateDownloadProjectFilteredMediaArchiveResponse = CreateDownloadProjectFilteredMediaArchiveResponses[keyof CreateDownloadProjectFilteredMediaArchiveResponses];

export type DownloadProjectFilteredMediaArchiveData = {
    body?: never;
    path: {
        'share-token': Token;
        'download-token': Token;
    };
    query?: {
        filename_format?: FilenameFormat;
    };
    url: '/projects/{share-token}/media/download/filtered/{download-token}';
};

export type DownloadProjectFilteredMediaArchiveErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails & {
        title: 'The request was malformed or invalid.';
        status: 400;
    };
    /**
     * The admin has not yet enabled downloads for this project.
     */
    403: ProblemDetails & {
        title: 'The admin has not yet enabled downloads for this project.';
        status: 403;
    };
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type DownloadProjectFilteredMediaArchiveError = DownloadProjectFilteredMediaArchiveErrors[keyof DownloadProjectFilteredMediaArchiveErrors];

export type DownloadProjectFilteredMediaArchiveResponses = {
    /**
     * Project media, archived as a zip or tar file. If mime type is application/octet-stream, the zip file is served.
     */
    200: DownloadFile;
};

export type DownloadProjectFilteredMediaArchiveResponse = DownloadProjectFilteredMediaArchiveResponses[keyof DownloadProjectFilteredMediaArchiveResponses];

export type GetProjectMediaData = {
    body?: never;
    path: {
        'share-token': Token;
        'media-id': MediaId;
    };
    query?: never;
    url: '/projects/{share-token}/media/{media-id}';
};

export type GetProjectMediaErrors = {
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type GetProjectMediaError = GetProjectMediaErrors[keyof GetProjectMediaErrors];

export type GetProjectMediaResponses = {
    /**
     * Media metadata
     */
    200: MediaMetadata;
};

export type GetProjectMediaResponse = GetProjectMediaResponses[keyof GetProjectMediaResponses];

export type UpdateProjectMediaData = {
    body: MediaMetadataUpdate;
    path: {
        'share-token': Token;
        'media-id': MediaId;
    };
    query?: never;
    url: '/projects/{share-token}/media/{media-id}';
};

export type UpdateProjectMediaErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails & {
        title: 'The request was malformed or invalid.';
        status: 400;
    };
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type UpdateProjectMediaError = UpdateProjectMediaErrors[keyof UpdateProjectMediaErrors];

export type UpdateProjectMediaResponses = {
    /**
     * Media metadata
     */
    200: MediaMetadata;
};

export type UpdateProjectMediaResponse = UpdateProjectMediaResponses[keyof UpdateProjectMediaResponses];

export type SyncProjectMediaFileData = {
    body: MediaMetadataTimesync;
    path: {
        'share-token': Token;
        'media-id': MediaId;
    };
    query?: never;
    url: '/projects/{share-token}/media/{media-id}/sync';
};

export type SyncProjectMediaFileErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails & {
        title: 'The request was malformed or invalid.';
        status: 400;
    };
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type SyncProjectMediaFileError = SyncProjectMediaFileErrors[keyof SyncProjectMediaFileErrors];

export type SyncProjectMediaFileResponses = {
    /**
     * The operation was performed successfully.
     */
    204: void;
};

export type SyncProjectMediaFileResponse = SyncProjectMediaFileResponses[keyof SyncProjectMediaFileResponses];

export type DownloadProjectMediaFileData = {
    body?: never;
    path: {
        'share-token': Token;
        'media-id': MediaId;
    };
    query?: {
        filename_format?: FilenameFormat;
    };
    url: '/projects/{share-token}/media/{media-id}/download';
};

export type DownloadProjectMediaFileErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails & {
        title: 'The request was malformed or invalid.';
        status: 400;
    };
    /**
     * The admin has not yet enabled downloads for this project.
     */
    403: ProblemDetails & {
        title: 'The admin has not yet enabled downloads for this project.';
        status: 403;
    };
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type DownloadProjectMediaFileError = DownloadProjectMediaFileErrors[keyof DownloadProjectMediaFileErrors];

export type DownloadProjectMediaFileResponses = {
    /**
     * A single media file
     */
    200: DownloadFile;
};

export type DownloadProjectMediaFileResponse = DownloadProjectMediaFileResponses[keyof DownloadProjectMediaFileResponses];

export type DownloadProjectMediaPreviewData = {
    body?: never;
    path: {
        'share-token': Token;
        'media-id': MediaId;
    };
    query?: {
        w?: number;
        h?: number;
        c?: PreviewCropMode;
    };
    url: '/projects/{share-token}/media/{media-id}/preview';
};

export type DownloadProjectMediaPreviewErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails & {
        title: 'The request was malformed or invalid.';
        status: 400;
    };
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * The server doesn't support previews for this media type.
     */
    422: ProblemDetails & {
        title: 'The server doesn\'t support previews for this media type.';
        status: 422;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type DownloadProjectMediaPreviewError = DownloadProjectMediaPreviewErrors[keyof DownloadProjectMediaPreviewErrors];

export type DownloadProjectMediaPreviewResponses = {
    /**
     * A media's preview image.
     */
    200: DownloadFile;
    /**
     * The media preview image has not been created yet. Try again later.
     */
    202: ProjectMediaPreviewNotReadyYet;
};

export type DownloadProjectMediaPreviewResponse = DownloadProjectMediaPreviewResponses[keyof DownloadProjectMediaPreviewResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        'admin-token': Token;
    };
    query?: never;
    url: '/admin/projects/{admin-token}';
};

export type DeleteProjectErrors = {
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * The project was deleted
     */
    204: void;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type PatchProjectData = {
    body: ProjectUpdate;
    path: {
        'admin-token': Token;
    };
    query?: never;
    url: '/admin/projects/{admin-token}';
};

export type PatchProjectErrors = {
    /**
     * The request was malformed or invalid
     */
    400: ProblemDetails & {
        title: 'The request was malformed or invalid.';
        status: 400;
    };
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type PatchProjectError = PatchProjectErrors[keyof PatchProjectErrors];

export type PatchProjectResponses = {
    /**
     * A single project
     */
    200: Project;
};

export type PatchProjectResponse = PatchProjectResponses[keyof PatchProjectResponses];

export type DeleteProjectUserData = {
    body?: never;
    path: {
        'admin-token': Token;
        'user-id': UserId;
    };
    query?: never;
    url: '/admin/projects/{admin-token}/users/{user-id}';
};

export type DeleteProjectUserErrors = {
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type DeleteProjectUserError = DeleteProjectUserErrors[keyof DeleteProjectUserErrors];

export type DeleteProjectUserResponses = {
    /**
     * The user was deleted
     */
    204: void;
};

export type DeleteProjectUserResponse = DeleteProjectUserResponses[keyof DeleteProjectUserResponses];

export type DeleteProjectMediaBatchedData = {
    body: MediaBatchDeletionRequest;
    path: {
        'admin-token': Token;
    };
    query?: never;
    url: '/admin/projects/{admin-token}/media/delete';
};

export type DeleteProjectMediaBatchedErrors = {
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type DeleteProjectMediaBatchedError = DeleteProjectMediaBatchedErrors[keyof DeleteProjectMediaBatchedErrors];

export type DeleteProjectMediaBatchedResponses = {
    /**
     * The media files were deleted
     */
    204: void;
};

export type DeleteProjectMediaBatchedResponse = DeleteProjectMediaBatchedResponses[keyof DeleteProjectMediaBatchedResponses];

export type DeleteProjectMediaData = {
    body?: never;
    path: {
        'admin-token': Token;
        'media-id': MediaId;
    };
    query?: never;
    url: '/admin/projects/{admin-token}/media/{media-id}';
};

export type DeleteProjectMediaErrors = {
    /**
     * The requested object was not found
     */
    404: ProblemDetails & {
        title: 'The requested object was not found.';
        status: 404;
    };
    /**
     * An internal server error occurred
     */
    500: ProblemDetails & {
        title: 'An internal server error has occured.';
        status: 500;
    };
};

export type DeleteProjectMediaError = DeleteProjectMediaErrors[keyof DeleteProjectMediaErrors];

export type DeleteProjectMediaResponses = {
    /**
     * The media was deleted
     */
    204: void;
};

export type DeleteProjectMediaResponse = DeleteProjectMediaResponses[keyof DeleteProjectMediaResponses];
