# Generated by Django 5.2.1 on 2025-09-02 13:22

import django.db.models.deletion
import ui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("suffix", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("suffix", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="members",
        ),
        migrations.RemoveField(
            model_name="project",
            name="created_at",
        ),
        migrations.AddField(
            model_name="project",
            name="done_ingesting",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.BigIntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("kept", models.BooleanField(default=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="ui.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProjectLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload_secret",
                    models.CharField(
                        default=ui.models.generate_secret, max_length=64, unique=True
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_links",
                        to="ui.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_links",
                        to="ui.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "project")},
            },
        ),
        migrations.AddField(
            model_name="device",
            name="user_project_link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="ui.userprojectlink",
            ),
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("user_project_link", "name")},
        ),
    ]
